services:
  mongodb:
    image: "mongo"
    volumes:
      - ts-docker-db:/data/db
    env_file:
      - ./secure-rest-api-with-docker/.env

  secure-rest-api-with-docker:
    build:
      context: ./secure-rest-api-with-docker
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    volumes:
      - ./secure-rest-api-with-docker:/app #bind mount
      - /app/node_modules #annonymous volume

    env_file:
      - ./secure-rest-api-with-docker/.env

    depends_on:
      - mongodb

volumes:
  ts-docker-db:
